### ISSUE TITLE
Environment and Town Testing

### ISSUE THREAD

**Issue by MrClemBETA** [MrClemBETA/2023VGDClass-UnityProject#6]
### Description
Create a simple environment using tutorials for Unity. Add some basic structures for a town that will be used in interaction testing.

### Requirements
- 500 by 500 unit environment with different elevations and textures
- Buildings and other obstacles that a character can interact with

**Comment by OMarshall42** [comment]
I practiced using the terrain tools and implementing assets from the unity store.

**Comment by MrClemBETA** [comment]
How is the practicing going? Is there a base environment that we can use (with trees, obstacles, buildings, etc) for character movement testing? Start thinking about and designing a true sandbox environment where we can test basic movement.

**Comment by threeskippers9** [comment]
10/25/2023
Today I worked on getting started on the terrain, I also made a new scene and watched a video tutorial of terrain tools.

Here is the video:
https://www.youtube.com/watch?v=sMNY980h5t8&t=397s

**Comment by OMarshall42** [comment]
I started trying to add new tree objects to my scene

Here is a screenshot
![Screenshot 2023-10-25 102631](https://github.com/MrClemBETA/2023VGDClass-UnityProject/assets/145701917/f2c01903-7c86-4dca-9d2a-dd5d037a1230)

**Comment by threeskippers9** [comment]
I started using terrain tools and made a cool looking mountain.

**Comment by GiovannyV16** [comment]
For two days of trying to do unity i had problems with downloads and the versions of unity so it left me to have time looking at more videos for building the terrains. as i was not as far as oliver but i was able too manage shaping the terrain into more of its sandy look and using the brushes to find which brush looks better.

And these are the vids i have been watching. their was more but i couldn't find them through a lot of them 

https://youtu.be/DbJB9534PZQ?si=0rLfun50xuXZEJci

https://youtu.be/MWQv2Bagwgk?si=o4eSUYdjzUfKLyxj

**Comment by OMarshall42** [comment]
I watched some youtube videos about adding assets into unity and started to look into new assets into the Unity store. I started to implement these assets and trying to make structures.

https://www.youtube.com/watch?v=AzItMI583kY

**Comment by MrClemBETA** [comment]
Work on getting 3 separate environment ready for push to the scrum.
- NavMesh: find videos and tutorials.

**Comment by GiovannyV16** [comment]
wasn't able to make a perfect environment as i was still finding out on how to use more of the terrain tools and then textures, as im gonna have to watch videos to make my work faster

**Comment by MrClemBETA** [comment]
A Basic Environment has been completed. Work will be done on more detail versions of demo environments.

**Comment by threeskippers9** [comment]
I added some trees to my terrain.

![Screenshot 2023-11-09 102601](https://github.com/MrClemBETA/2023VGDClass-UnityProject/assets/145701767/12d0181a-85fc-4306-8212-01d012a20ecd)

**Comment by threeskippers9** [comment]
I added some more structures in my terrain, and I also tried to make a castle out of rocks but i failed.

**Comment by threeskippers9** [comment]
Today I finished my terrain and included some objects, here is a slight look at my terrain.

![Screenshot 2023-11-14 094909](https://github.com/MrClemBETA/2023VGDClass-UnityProject/assets/145701767/f29f80ee-9746-4bb7-bb7d-139ec1d8f10e)
