### ISSUE TITLE
Basic 3D Character Movement and Camera Manipulation

### ISSUE THREAD

**Issue by MrClemBETA** [MrClemBETA/2023VGDClass-UnityProject#7]
### Description
Create a simple 3D character in a simple environment (just a basic floor) and work on character movement with 1st and 3rd person camera manipulation and follow.

### Requirements
- Research and reuse basic 3D character movement.
- Implement 3rd Person and 1st Person camera movement
- Keybind a command to change the camera between states

**Comment by TylerGaming101** [comment]
Made basic player movement and camera following the player

**Comment by TylerGaming101** [comment]
Added sprint feature

**Comment by Noah-C138** [comment]
I am in the process of making a script for a 3rd and 1st person camera view

**Comment by MrClemBETA** [comment]
@TylerGaming101 and @Noah-C138 are you guys duplicating efforts here? Let's take some time to look at the systems in place so that when we go through the testing phase, things make sense. Remember, if there is a big task that we break down into smaller tasks, we should not be working on the same small tasks. We want to make sure that the smaller tasks are independent enough where we are not duplicating efforts or stepping on each other's toes.

**Comment by TylerGaming101** [comment]
Progress mostly reset. Nothing that could be done.

**Comment by TylerGaming101** [comment]
Player movement readded, however the jump feature is gone somehow??? Player floats slightly above ground, making the isGrounded variable permanently false. It was working yesterday even after the accidental git pull. 

Something also happened to the manifest .json, something might've happened while I tried to git pull

**Comment by MrClemBETA** [comment]
Branch is not ready for merge to scrum 2.

- Fixing the jump mechanic to be able to merge to scrum 3.
- Determine extra feature for this scrum.

**Comment by TylerGaming101** [comment]
Started working on the healthbar using the canvas and Text Mesh Pro

**Comment by MrClemBETA** [comment]
Basic character movement achieved. Need to work on character camera movement.
