### ISSUE TITLE
Inventory System

### ISSUE THREAD

**Issue by MrClemBETA** [MrClemBETA/2023VGDClass-UnityProject#8]
### Description
Research and determine a valid inventory system for the game. Determine item types, inventory organization, required stats for item types, weight and encumbrance system.

### Requirements
- Research existing inventory systems and free Unity assets.
- Determine an organizational system for the inventory (outside of Unity).
- Determine item types and traits for each item type (i.e., weapons have damage, handedness, durability, enhancement, etc.)
- Determine how encumbrance works in this game and implement the system.

**Comment by JTorriente** [comment]
I watched videos on how to make a inventory

**Comment by JTorriente** [comment]
I researched an organizational system

**Comment by MrClemBETA** [comment]
Let's get some more information here. Do you have links to the systems you researched? Do you have links to the videos? What were the pros and cons of each system? Is making our own system something that is feasible, or do we want to borrow a system?

**Comment by JTorriente** [comment]
making our own inventory system is feasible I watched this video: https://www.youtube.com/watch?v=SGz3sbZkfkg, the pros were that there is code for making our own assets,

**Comment by MrClemBETA** [comment]
Scrum 3 - Determine Inventory style: categorizing items, providing attributes, determining temp prefabs for analysis.
- Start inventory creation.

**Comment by JTorriente** [comment]
I researched different inventory systems and figured out how to add enchantment and other things to the item in an inventory, I would need to know the weapon art and stats so I can implement the enchantments on the item
